export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';

export const FIND_COMMENTS_BY_POST_REQUEST = 'FIND_COMMENTS_BY_POST_REQUEST';
export const FIND_COMMENTS_BY_POST_SUCCESS = 'FIND_COMMENTS_BY_POST_SUCCESS';
export const FIND_COMMENTS_BY_POST_FAILURE = 'FIND_COMMENTS_BY_POST_FAILURE';

export const LIKE_COMMENT_REQUEST = 'LIKE_COMMENT_REQUEST';
export const LIKE_COMMENT_SUCCESS = 'LIKE_COMMENT_SUCCESS';
export const LIKE_COMMENT_FAILURE = 'LIKE_COMMENT_FAILURE';

export const DELETE_ADMIN_COMMENT_REQUEST = 'DELETE_ADMIN_COMMENT_REQUEST';
export const DELETE_ADMIN_COMMENT_SUCCESS = 'DELETE_ADMIN_COMMENT_SUCCESS';
export const DELETE_ADMIN_COMMENT_FAILURE = 'DELETE_ADMIN_COMMENT_FAILURE';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILURE = 'DELETE_COMMENT_FAILURE';

