export const CREATE_MESSAGE_REQUEST = 'CREATE_MESSAGE_REQUEST';
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS';
export const CREATE_MESSAGE_FAILURE = 'CREATE_MESSAGE_FAILURE';

export const FIND_CHAT_MESSAGES_REQUEST = 'FIND_CHAT_MESSAGES_REQUEST';
export const FIND_CHAT_MESSAGES_SUCCESS = 'FIND_CHAT_MESSAGES_SUCCESS';
export const FIND_CHAT_MESSAGES_FAILURE = 'FIND_CHAT_MESSAGES_FAILURE';

export const DELETE_ADMIN_MESSAGE_REQUEST = 'DELETE_ADMIN_MESSAGE_REQUEST';
export const DELETE_ADMIN_MESSAGE_SUCCESS = 'DELETE_ADMIN_MESSAGE_SUCCESS';
export const DELETE_ADMIN_MESSAGE_FAILURE = 'DELETE_ADMIN_MESSAGE_FAILURE';
