export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';

export const FIND_USER_POSTS_REQUEST = 'FIND_USER_POSTS_REQUEST';
export const FIND_USER_POSTS_SUCCESS = 'FIND_USER_POSTS_SUCCESS';
export const FIND_USER_POSTS_FAILURE = 'FIND_USER_POSTS_FAILURE';

export const FIND_ALL_POSTS_REQUEST = 'FIND_ALL_POSTS_REQUEST';
export const FIND_ALL_POSTS_SUCCESS = 'FIND_ALL_POSTS_SUCCESS';
export const FIND_ALL_POSTS_FAILURE = 'FIND_ALL_POSTS_FAILURE';

export const SAVE_POST_REQUEST = 'SAVE_POST_REQUEST';
export const SAVE_POST_SUCCESS = 'SAVE_POST_SUCCESS';
export const SAVE_POST_FAILURE = 'SAVE_POST_FAILURE';

export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_FAILURE = 'LIKE_POST_FAILURE';

export const FIND_TOP_POSTS_REQUEST = 'FIND_TOP_POSTS_REQUEST';
export const FIND_TOP_POSTS_SUCCESS = 'FIND_TOP_POSTS_SUCCESS';
export const FIND_TOP_POSTS_FAILURE = 'FIND_TOP_POSTS_FAILURE';

export const DELETE_ADMIN_POST_REQUEST = 'DELETE_ADMIN_POST_REQUEST';
export const DELETE_ADMIN_POST_SUCCESS = 'DELETE_ADMIN_POST_SUCCESS';
export const DELETE_ADMIN_POST_FAILURE = 'DELETE_ADMIN_POST_FAILURE';