export const CREATE_CHAT_REQUEST = 'CREATE_CHAT_REQUEST';
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS';
export const CREATE_CHAT_FAILURE = 'CREATE_CHAT_FAILURE';

export const FIND_USER_CHATS_REQUEST = 'FIND_USER_CHATS_REQUEST';
export const FIND_USER_CHATS_SUCCESS = 'FIND_USER_CHATS_SUCCESS';
export const FIND_USER_CHATS_FAILURE = 'FIND_USER_CHATS_FAILURE';

export const FIND_ALL_CHATS_REQUEST = 'FIND_ALL_CHATS_REQUEST';
export const FIND_ALL_CHATS_SUCCESS = 'FIND_ALL_CHATS_SUCCESS';
export const FIND_ALL_CHATS_FAILURE = 'FIND_ALL_CHATS_FAILURE';

export const DELETE_ADMIN_CHAT_REQUEST = 'DELETE_ADMIN_CHAT_REQUEST';
export const DELETE_ADMIN_CHAT_SUCCESS = 'DELETE_ADMIN_CHAT_SUCCESS';
export const DELETE_ADMIN_CHAT_FAILURE = 'DELETE_ADMIN_CHAT_FAILURE';

export const DELETE_CHAT_REQUEST = 'DELETE_CHAT_REQUEST';
export const DELETE_CHAT_SUCCESS = 'DELETE_CHAT_SUCCESS';
export const DELETE_CHAT_FAILURE = 'DELETE_CHAT_FAILURE';